apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: GitHubTest
  labels:
    access: private
spec:
  type: single-use
  lifecycle: deprecated
  owner: test
  definition: |
    {
      "openapi": "3.1.0"
      "info": {
        "version": "2022-01-01"
        "title": "GitHubTest"
      }
    }
