apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: GitHubTest
  labels:
    access: private
  tags: []
spec:
  type: business domain
  lifecycle: design
  owner: test
  definition: |
    {
      "openapi": "3.0.1",
      "info": {
        "version": "2022-01-01",
        "title": "GitHubTest"
      }
    }
